title: CryptoChainery # your site title
author: VKR
description: > # Meta description of Homepage
  CryptoChainary aims at being a one-stop resource for blockchain and bitcoin technology. My goal 
  is learn and help people learn about blockchain technology which can truly transform certain aspects of the industry
  as we know it. I am always on the lookout for new and interesting applications of blockchain technology - 
  so if you want to exchange ideas or simply get it touch, please send me an email and let's get talking. Thank you!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cryptochainery.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
email : cryptochainery@gmail.com

# social links
# twitter_username: jekyllrb
# github_username:  jekyll
rss: rss
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
# linkedin_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll

# Mastodon instances
# mastodon:
# - username: jekyll
#   instance: example.com
# - username: jekyll2
#   instance: example.com


show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
